spring:
  application:
    name: adminService
  profiles:
    active: dev
  config:
      import: optional:configserver:http://miracle:1234@localhost:60010

eureka:
  client:
    service-url:
      defaultZone: http://miracle:1234@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true